version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.1.0
  codequality: blackbuck/codequality@0.0.2
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  deploy:
    executor: aws-cli/default
    environment:
      NEW_INSTANCE_NAME: circleci
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
      - add_ssh_keys:
          fingerprints:
            - "SHA256:u058n7JzYAn2CsIuZD2z9DPedUzJanC7bp7e0JN09/8"
      - run:
          command: ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa* ubuntu@$INSTANCE_IP "sudo apt install curl unzip -y && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -o awscliv2.zip  && sudo ./aws/install --update"
          name: Installing AWS CLI
      - run:
          command: ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa* ubuntu@$INSTANCE_IP "sudo apt update && sudo apt install python3 -y"
          name: install python
      - run:
          command: ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa* ubuntu@$INSTANCE_IP
            "sudo apt-get update &&
            sudo apt-get install ca-certificates curl &&
            sudo install -m 0755 -d /etc/apt/keyrings &&
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc &&
            sudo chmod a+r /etc/apt/keyrings/docker.asc &&
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&
            sudo apt-get update &&
            sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y"
          name: install docker
      - run:
          command: ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa* ubuntu@$INSTANCE_IP "aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} && aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} && aws configure set default.region ${AWS_REGION}"
          name: Configure AWS
      - run:
          command: ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa* ubuntu@$INSTANCE_IP "aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com && sudo docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/django-circleci-reg:latest"
          name: IMAGE pull
      - run:
          command: ssh -o StrictHostKeyChecking=accept-new -i $HOME/.ssh/id_rsa* ubuntu@$INSTANCE_IP "sudo docker compose up -d"

  build_and_test:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_REGION
      - aws-ecr/build_image:
          account_id: ${AWS_ACCOUNT_ID}
          repo: django-circleci-reg
          path: .
          region: ${AWS_REGION}
          dockerfile: Dockerfile
          push_image: false

      - run:
          command: echo "Run Tests"
          name: Run Tests

      - run:
          command: mkdir workspace && docker save ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/django-circleci-reg:latest -o workspace/image.tar

      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar

  scan_image:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: workspace
      - run:
          command: sudo docker load -i workspace/image.tar
      - codequality/scan:
          project_key: test_scan
          workspace_path: .
  
  push-image:
    executor: aws-ecr/default
    steps:
      - attach_workspace:
          at: /var/lib/docker
      - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_REGION
      - aws-ecr/push_image:
          account_id: ${AWS_ACCOUNT_ID}
          repo: django-circleci-reg
          region: ${AWS_REGION}

  





workflows:
  build_and_push_image:
    jobs:
      # - aws-ecr/build_and_push_image:
      #     account_id: ${AWS_ACCOUNT_ID}
      #     auth:
      #       - aws-cli/setup:
      #           aws_access_key_id: AWS_ACCESS_KEY_ID
      #           aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      #           region: AWS_REGION
      #     context: aws-ecr
      #     create_repo: true
      #     dockerfile: Dockerfile
      #     region: ${AWS_REGION}
      #     path: .
      #     repo: django-circleci-reg
      - build_and_test:
          context: aws-ecr
      
      - scan_image:
          requires:
            - build_and_test
          context: aws-ecr
      # - test:
      #     context: aws-ecr
      #     requires:
      #       - build

      - hold:
          type: approval
          requires:
            - build_and_test


      # - deploy:
      #     requires:
      #       - hold
      #       # - aws-ecr/build_and_push_image
      #     context: aws-ecr